name: manage-azure-policy
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'src/policies/cit-security-disable_rdp_internet/**'
#      - 'src/policies/cit-storage-enforce_geo_redundancy/**'
#      - 'src/policies/cit-storage-enforce_secure_transfer/**'
#      - 'src/policies/cit-vm-allowed_os_skus/**'
#      - 'src/policies/cit-vm-deny_unmanaged_disks/**'
#      - .github/workflows/manage-azure-policy-88ad210d.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_88ad210d}}
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          src/policies/cit-security-disable_rdp_internet/**
          src/policies/cit-storage-enforce_geo_redundancy/**
          src/policies/cit-storage-enforce_secure_transfer/**
          src/policies/cit-vm-allowed_os_skus/**
          src/policies/cit-vm-deny_unmanaged_disks/**
        mode: complete
